### ISSUE TITLE
brak subskrybentów na streamie -> error 503

### ISSUE THREAD

**Issue by ernestworkspace** [AkondLab/serverish#2]
Gdy publikuje wiadomość za pomocą serverish w streamie dostaje błąd `nats.js.errors.NoStreamResponseError`.  Po sprawdzeniu sreama okazuje się że wiadomośc została poprawnie dodana i można ją pobrać. Przyczyną tego jest prawdopodobnie mechanizm opisany tutaj https://docs.nats.io/nats-concepts/core-nats/reqreply być może warto było by w serverish zakleić to jakoś.

**Comment by majkelx** [comment]
Nie sądzę żeby to była przyczyna Req-Resp to specjalny case.

**Comment by majkelx** [comment]
Albo jakoś stream się skonfigurował Ci na taki do ReqResp

**Comment by ernestworkspace** [comment]
faktycznie problemem był źle skonfigurowany stream. Problem rozwiązało ustawienie w konfiguracji streamie parametru `NoAck = false`
